FROM arm64v8/python:3.7-slim-buster

WORKDIR /app

#additional pckages need to make cffi working
RUN apt-get update
RUN apt-get install -y build-essential libi2c-dev libffi-dev

COPY requirements.txt ./
RUN pip install -r requirements.txt

COPY . .

CMD [ "python3", "-u", "./main.py" ]